image: gitpod/workspace-full

tasks:
  - name: initialisation de boost
    command: sudo apt-get install -y libboost1.71-all-dev lcov gcovr libgtest-dev libgmock-dev
  - name: init des variables d'env
    env:
      MY_VAR: OKI_DOKI_MA_VARIABLE
    
